Fix negative timeout crash
Previously a timeout on one of the calendars could cause the following crash:

    Traceback (most recent call last):
      File "/home/user/src/ots/opentimestamps-client/ots-git-gpg-wrapper", line 133, in <module>
        otsclient.cmds.create_timestamp(final_timestamp, args.calendar_urls, args)
      File "/home/user/src/ots/opentimestamps-client/otsclient/cmds.py", line 111, in create_timestamp
        result = q.get(block=True, timeout=remaining)
      File "/usr/lib/python3.4/queue.py", line 169, in get
        raise ValueError("'timeout' must be a non-negative number")
    ValueError: 'timeout' must be a non-negative number

Ensuring the timeout is always non-negative fixes this.